### ISSUE TITLE
ContextSymbol.getModules() returns duplicated modules

### ISSUE THREAD

**Issue by ghsyeung** [mgechev/ngast#1]
Since `NgAnalyzedModules.ngModuleByPipeOrDirective` returns a map, and `getModules` uses only the values. There are multiple references/clones of the same module metadata (like `CommonModule`) returned by getModules().

Looks like we need to de-dupe by `type.reference`.

**Comment by mgechev** [comment]
Do you have time for a quick PR? Otherwise, I can address this issue early next week.

**Comment by ghsyeung** [comment]
Yeah I'll put a test case and PR tomorrow.
