### ISSUE TITLE
Support for older angular compiler versions

### ISSUE THREAD

**Issue by elgrandt** [mgechev/ngast#49]
I'm trying to analyse an angular 7 project and I'm getting some errors because this library is trying to compile it with the angular 11 compiler, is there a way to overcome this problem?
Thank you

**Comment by irustm** [comment]
@elgrandt I think you can use older version - ngast@0.2.5 

----
https://www.npmjs.com/package/ngast?activeTab=dependencies

**Comment by elgrandt** [comment]
@irustm that's true, I tried it, but that version has a lot less functionality than the current one, so I would have to rebuild my code.

**Comment by mgechev** [comment]
Realistically, I'd not have the bandwidth to implement this feature. If anyone wants to contribute will be happy to help with a review. Closing until anyone claims the issue :)
